name: test-ymal
on:
    push:
        branches:
            - main 
    pull_request:
        branches:
             - main
        paths:
               - "src/**"
jobs:
    exampel:
       runs-on: ubuntu-22.04
       steps:
        - name : print
          run : echo " welcome"    
        - name: Run tests
          run : npm test                   